import type { PsychologicalCategory, QuestModel, QuestPace } from '../types';

/** Fenêtre max pour reporter une quête « planifiée » (choix de date côté client + API). */
export const REPORT_DEFER_MAX_DAYS = 14;

/**
 * Rythme d’archétype : social ou durée ≥ 6 h → planifiée ; sinon instantanée (faisable dans la journée).
 */
export function archetypeQuestPace(q: {
  requiresSocial: boolean;
  minimumDurationMinutes: number;
}): QuestPace {
  if (q.requiresSocial) return 'planned';
  if (q.minimumDurationMinutes >= 360) return 'planned';
  return 'instant';
}

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

/** Date de report (YYYY-MM-DD) dans [today, today+REPORT_DEFER_MAX_DAYS] (référence midi UTC). */
export function isValidReportDeferredDate(dateIso: string, todayIso: string): boolean {
  if (!ISO_DATE.test(dateIso) || !ISO_DATE.test(todayIso)) return false;
  const t0 = Date.parse(`${todayIso}T12:00:00.000Z`);
  const t1 = Date.parse(`${dateIso}T12:00:00.000Z`);
  if (Number.isNaN(t0) || Number.isNaN(t1)) return false;
  const max = t0 + REPORT_DEFER_MAX_DAYS * 86400000;
  return t1 >= t0 && t1 <= max;
}

const _QUEST_TAXONOMY_RAW: ReadonlyArray<Omit<QuestModel, 'questPace'>> = [
  {
    id: 1,
    title: 'Le Voyage Aléatoire',
    description: 'Prendre un train vers une ville au hasard et se débrouiller une fois arrivé.',
    category: 'spatial_adventure',
    targetTraits: { openness: 0.95, emotionalStability: 0.7 },
    comfortLevel: 'extreme',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 480,
    fallbackQuestId: 9,
  },
  {
    id: 2,
    title: 'Le Dîner Solitaire',
    description: 'Manger seul dans un resto chic. Téléphone éteint. Être à l\'aise avec soi-même.',
    category: 'public_introspection',
    targetTraits: { emotionalStability: 0.8, extraversion: 0.3 },
    comfortLevel: 'high',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 90,
    fallbackQuestId: 9,
  },
  {
    id: 3,
    title: 'La Nuit Étoilée',
    description: 'Passer une nuit sous les étoiles, sans distraction, juste avec ses pensées.',
    category: 'sensory_deprivation',
    targetTraits: { openness: 0.6, conscientiousness: 0.5 },
    comfortLevel: 'high',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 600,
    fallbackQuestId: 9,
  },
  {
    id: 4,
    title: 'L\'Explorateur Local',
    description: 'Aller dans une ville minuscule et parler à au moins une personne locale.',
    category: 'exploratory_sociability',
    targetTraits: { extraversion: 0.7, agreeableness: 0.6, openness: 0.7 },
    comfortLevel: 'high',
    requiresOutdoor: true,
    requiresSocial: true,
    minimumDurationMinutes: 240,
    fallbackQuestId: 13,
  },
  {
    id: 5,
    title: 'Le Point Culminant',
    description: 'Monter au point le plus haut de la ville et réfléchir à sa direction de vie.',
    category: 'physical_existential',
    targetTraits: { openness: 0.6, conscientiousness: 0.5 },
    comfortLevel: 'moderate',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 120,
    fallbackQuestId: 9,
  },
  {
    id: 6,
    title: 'L\'Entraînement de l\'Aube',
    description: 'S\'entraîner seul un dimanche matin pendant que tout le monde dort.',
    category: 'async_discipline',
    targetTraits: { conscientiousness: 0.9 },
    comfortLevel: 'moderate',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 60,
    fallbackQuestId: 9,
  },
  {
    id: 7,
    title: 'La Détox Digitale',
    description: 'Passer 24h sans réseaux sociaux et observer les changements cognitifs.',
    category: 'dopamine_detox',
    targetTraits: { emotionalStability: 0.7, conscientiousness: 0.8 },
    comfortLevel: 'high',
    requiresOutdoor: false,
    requiresSocial: false,
    minimumDurationMinutes: 1440,
  },
  {
    id: 8,
    title: 'Le Pont Humain',
    description: 'Lancer une vraie conversation avec un inconnu. Écouter vraiment.',
    category: 'active_empathy',
    targetTraits: { extraversion: 0.8, agreeableness: 0.8 },
    comfortLevel: 'high',
    requiresOutdoor: true,
    requiresSocial: true,
    minimumDurationMinutes: 30,
    fallbackQuestId: 12,
  },
  {
    id: 9,
    title: 'La Lettre au Futur',
    description: 'Écrire une lettre à la personne que l\'on veut devenir dans 5 ans.',
    category: 'temporal_projection',
    targetTraits: { openness: 0.5, conscientiousness: 0.6 },
    comfortLevel: 'low',
    requiresOutdoor: false,
    requiresSocial: false,
    minimumDurationMinutes: 45,
  },
  {
    id: 10,
    title: 'L\'Immersion Totale',
    description: 'Aller à un événement où l\'on ne connaît personne et rester jusqu\'à être à l\'aise.',
    category: 'hostile_immersion',
    targetTraits: { extraversion: 0.9, emotionalStability: 0.8 },
    comfortLevel: 'extreme',
    requiresOutdoor: true,
    requiresSocial: true,
    minimumDurationMinutes: 180,
    fallbackQuestId: 8,
  },
  {
    id: 11,
    title: 'Le Rayon de Soleil',
    description: 'Complimenter sincèrement cinq inconnus dans la même journée.',
    category: 'spontaneous_altruism',
    targetTraits: { agreeableness: 0.7, extraversion: 0.6 },
    comfortLevel: 'moderate',
    requiresOutdoor: true,
    requiresSocial: true,
    minimumDurationMinutes: 60,
    fallbackQuestId: 13,
  },
  {
    id: 12,
    title: 'La Reconnexion',
    description: 'Appeler un ancien ami et rallumer un lien laissé éteint.',
    category: 'relational_vulnerability',
    targetTraits: { agreeableness: 0.7, emotionalStability: 0.6 },
    comfortLevel: 'high',
    requiresOutdoor: false,
    requiresSocial: true,
    minimumDurationMinutes: 30,
  },
  {
    id: 13,
    title: 'Le Festin Altruiste',
    description: 'Cuisiner un repas pour quelqu\'un sans rien attendre en retour.',
    category: 'unconditional_service',
    targetTraits: { agreeableness: 0.8, conscientiousness: 0.6 },
    comfortLevel: 'low',
    requiresOutdoor: false,
    requiresSocial: true,
    minimumDurationMinutes: 120,
  },
  {
    id: 14,
    title: 'Le Regret des Anciens',
    description: 'Demander à une personne plus âgée son plus grand regret. Écouter sans juger.',
    category: 'active_empathy',
    targetTraits: { agreeableness: 0.85, extraversion: 0.55, emotionalStability: 0.65 },
    comfortLevel: 'high',
    requiresOutdoor: false,
    requiresSocial: true,
    minimumDurationMinutes: 45,
    fallbackQuestId: 8,
  },
  {
    id: 15,
    title: 'La Lecture Profonde',
    description: 'Lire 50 pages d\'un livre exigeant en une journée, sans distraction.',
    category: 'dopamine_detox',
    targetTraits: { conscientiousness: 0.85, openness: 0.7 },
    comfortLevel: 'high',
    requiresOutdoor: false,
    requiresSocial: false,
    minimumDurationMinutes: 240,
    fallbackQuestId: 7,
  },
  {
    id: 16,
    title: 'Le Narrateur Intérieur',
    description: 'Écrire ton journal intime à la troisième personne. Te voir comme un personnage.',
    category: 'temporal_projection',
    targetTraits: { openness: 0.75, conscientiousness: 0.55 },
    comfortLevel: 'moderate',
    requiresOutdoor: false,
    requiresSocial: false,
    minimumDurationMinutes: 60,
    fallbackQuestId: 9,
  },
  {
    id: 17,
    title: 'Le Plan sans Égo',
    description: 'Une séance de sport où tu respectes exactement le plan. Discipline avant ego.',
    category: 'async_discipline',
    targetTraits: { conscientiousness: 0.92, emotionalStability: 0.65 },
    comfortLevel: 'moderate',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 60,
    fallbackQuestId: 6,
  },
  {
    id: 18,
    title: 'L\'Œil Nu',
    description: 'Prendre 30 photos en une heure sans filtre ni retouche. Apprendre à voir le réel.',
    category: 'sensory_deprivation',
    targetTraits: { openness: 0.65, conscientiousness: 0.55 },
    comfortLevel: 'moderate',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 60,
    fallbackQuestId: 3,
  },
  {
    id: 19,
    title: 'Le Grand Rangement',
    description: 'Réorganiser entièrement un espace de vie (pièce ou zone majeure) jusqu\'au bout.',
    category: 'async_discipline',
    targetTraits: { conscientiousness: 0.88 },
    comfortLevel: 'moderate',
    requiresOutdoor: false,
    requiresSocial: false,
    minimumDurationMinutes: 180,
    fallbackQuestId: 9,
  },
  {
    id: 20,
    title: 'La Vie Hardie',
    description: 'Écrire l\'histoire de ta vie si tu avais eu plus de courage.',
    category: 'temporal_projection',
    targetTraits: { openness: 0.8, emotionalStability: 0.55 },
    comfortLevel: 'high',
    requiresOutdoor: false,
    requiresSocial: false,
    minimumDurationMinutes: 120,
    fallbackQuestId: 9,
  },
  {
    id: 21,
    title: 'La Bande-Son du Futur',
    description: 'Créer une playlist pour la version de toi que tu es en train de devenir.',
    category: 'temporal_projection',
    targetTraits: { openness: 0.75, conscientiousness: 0.5 },
    comfortLevel: 'low',
    requiresOutdoor: false,
    requiresSocial: false,
    minimumDurationMinutes: 60,
    fallbackQuestId: 9,
  },
  {
    id: 22,
    title: 'La Journée Sans Mensonge',
    description: 'Pendant une journée entière, ne dire que la vérité (avec tact). Observer le coût et le soulagement.',
    category: 'relational_vulnerability',
    targetTraits: { agreeableness: 0.65, emotionalStability: 0.7 },
    comfortLevel: 'extreme',
    requiresOutdoor: false,
    requiresSocial: true,
    minimumDurationMinutes: 1440,
    fallbackQuestId: 12,
  },
  {
    id: 23,
    title: 'Le Micro-Défi',
    description: 'Faire une chose qui te fait légèrement peur, juste pour prouver que tu peux.',
    category: 'physical_existential',
    targetTraits: { openness: 0.85, emotionalStability: 0.6 },
    comfortLevel: 'moderate',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 30,
    fallbackQuestId: 5,
  },
  {
    id: 24,
    title: 'La Semaine Vitale',
    description: 'Planifier une semaine complète comme si ta vie en dépendait : blocs, priorités, imprévus.',
    category: 'async_discipline',
    targetTraits: { conscientiousness: 0.95, openness: 0.45 },
    comfortLevel: 'high',
    requiresOutdoor: false,
    requiresSocial: false,
    minimumDurationMinutes: 90,
    fallbackQuestId: 9,
  },
  {
    id: 25,
    title: 'L\'Arrêt Inconnu',
    description: 'Prendre une ligne de bus que tu n\'empruntes jamais, descendre à un arrêt au hasard et marcher 20 minutes sans itinéraire fixé.',
    category: 'spatial_adventure',
    targetTraits: { openness: 0.9, emotionalStability: 0.65 },
    comfortLevel: 'high',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 120,
    fallbackQuestId: 1,
  },
  {
    id: 26,
    title: 'Le Banc Silencieux',
    description: 'Rester assis seul sur un banc public 30 minutes : pas d\'écran, pas de casque, seulement présence.',
    category: 'public_introspection',
    targetTraits: { emotionalStability: 0.75, extraversion: 0.35 },
    comfortLevel: 'moderate',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 30,
    fallbackQuestId: 2,
  },
  {
    id: 27,
    title: 'La Marche Sans Musique',
    description: 'Une promenade d\'au moins 20 minutes en silence total, sans musique ni podcast.',
    category: 'sensory_deprivation',
    targetTraits: { openness: 0.55, conscientiousness: 0.5 },
    comfortLevel: 'low',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 20,
    fallbackQuestId: 3,
  },
  {
    id: 28,
    title: 'Le Lieu du Commerçant',
    description: 'Demander à un commerçant local son endroit préféré dans le coin et s\'y rendre une fois.',
    category: 'exploratory_sociability',
    targetTraits: { extraversion: 0.65, agreeableness: 0.65, openness: 0.7 },
    comfortLevel: 'moderate',
    requiresOutdoor: true,
    requiresSocial: true,
    minimumDurationMinutes: 120,
    fallbackQuestId: 4,
  },
  {
    id: 29,
    title: 'Le Trajet Lent',
    description: 'Refaire un trajet habituel à pied ou à vélo au lieu des transports ; noter une pensée à mi-parcours.',
    category: 'physical_existential',
    targetTraits: { conscientiousness: 0.55, openness: 0.6 },
    comfortLevel: 'moderate',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 90,
    fallbackQuestId: 5,
  },
  {
    id: 30,
    title: 'La Soirée Analogique',
    description: 'Une soirée complète sans aucun écran après une heure fixée (lecture papier, conversation, repos).',
    category: 'dopamine_detox',
    targetTraits: { conscientiousness: 0.75, emotionalStability: 0.65 },
    comfortLevel: 'moderate',
    requiresOutdoor: false,
    requiresSocial: false,
    minimumDurationMinutes: 180,
    fallbackQuestId: 7,
  },
  {
    id: 31,
    title: 'L\'Écoute Profonde',
    description: 'Poser une question ouverte à quelqu\'un et ne parler que pour reformuler ou approfondir pendant 10 minutes.',
    category: 'active_empathy',
    targetTraits: { agreeableness: 0.85, extraversion: 0.55 },
    comfortLevel: 'moderate',
    requiresOutdoor: false,
    requiresSocial: true,
    minimumDurationMinutes: 15,
    fallbackQuestId: 8,
  },
  {
    id: 32,
    title: 'La Lettre du Non',
    description: 'Écrire une page adressée à une version de toi qui dit toujours non par peur : ce que tu lui refuserais encore.',
    category: 'temporal_projection',
    targetTraits: { openness: 0.7, emotionalStability: 0.55 },
    comfortLevel: 'high',
    requiresOutdoor: false,
    requiresSocial: false,
    minimumDurationMinutes: 45,
    fallbackQuestId: 9,
  },
  {
    id: 33,
    title: 'L\'Autre Monde',
    description: 'Passer au moins une heure dans un lieu où tu te sens minoritaire (langue, âge, scène) et rester jusqu\'à être un peu à l\'aise.',
    category: 'hostile_immersion',
    targetTraits: { extraversion: 0.75, emotionalStability: 0.75, openness: 0.7 },
    comfortLevel: 'extreme',
    requiresOutdoor: true,
    requiresSocial: true,
    minimumDurationMinutes: 120,
    fallbackQuestId: 10,
  },
  {
    id: 34,
    title: 'Le Mot Égaré',
    description: 'Laisser un mot manuscrit d\'encouragement dans un lieu public (sans signature narcissique).',
    category: 'spontaneous_altruism',
    targetTraits: { agreeableness: 0.75, extraversion: 0.5 },
    comfortLevel: 'moderate',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 45,
    fallbackQuestId: 11,
  },
  {
    id: 35,
    title: 'Le Remerciement Tardif',
    description: 'Dire à un proche une chose précise que tu apprécies chez lui depuis longtemps sans l\'avoir dit.',
    category: 'relational_vulnerability',
    targetTraits: { agreeableness: 0.75, emotionalStability: 0.6 },
    comfortLevel: 'high',
    requiresOutdoor: false,
    requiresSocial: true,
    minimumDurationMinutes: 30,
    fallbackQuestId: 12,
  },
  {
    id: 36,
    title: 'Le Cadeau Sans Occasion',
    description: 'Offrir un petit cadeau ou un repas à un voisin ou un collègue sans occasion particulière.',
    category: 'unconditional_service',
    targetTraits: { agreeableness: 0.85, conscientiousness: 0.55 },
    comfortLevel: 'moderate',
    requiresOutdoor: false,
    requiresSocial: true,
    minimumDurationMinutes: 90,
    fallbackQuestId: 13,
  },
];

export const QUEST_TAXONOMY: QuestModel[] = _QUEST_TAXONOMY_RAW.map((q) => ({
  ...q,
  questPace: archetypeQuestPace(q),
}));

export const INDOOR_QUEST_IDS = QUEST_TAXONOMY
  .filter((q) => !q.requiresOutdoor)
  .map((q) => q.id);

export const FALLBACK_QUEST_ID = 9;

/** Famille de quête (moteur) — libellé court, distinct du titre généré par l’IA */
export const QUEST_CATEGORY_LABEL_FR: Record<PsychologicalCategory, string> = {
  spatial_adventure: 'Déplacement & exploration',
  public_introspection: 'Présence en public',
  sensory_deprivation: 'Immersion & calme',
  exploratory_sociability: 'Rencontre & lieu',
  physical_existential: 'Corps & perspective',
  async_discipline: 'Discipline & rythme',
  dopamine_detox: 'Rythme & écrans',
  active_empathy: 'Connexion & écoute',
  temporal_projection: 'Projection',
  hostile_immersion: 'Immersion sociale',
  spontaneous_altruism: 'Geste & chaleur',
  relational_vulnerability: 'Liens proches',
  unconditional_service: 'Don & partage',
};

export function questFamilyLabel(category: string | undefined | null): string | null {
  if (!category) return null;
  const k = category as PsychologicalCategory;
  return k in QUEST_CATEGORY_LABEL_FR ? QUEST_CATEGORY_LABEL_FR[k] : null;
}
