import type { PsychologicalCategory, QuestModel } from '../types';

export const QUEST_TAXONOMY: QuestModel[] = [
  {
    id: 1,
    title: 'Le Voyage Aléatoire',
    description: 'Prendre un train vers une ville au hasard et se débrouiller une fois arrivé.',
    category: 'spatial_adventure',
    targetTraits: { openness: 0.95, emotionalStability: 0.7 },
    comfortLevel: 'extreme',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 480,
    fallbackQuestId: 9,
  },
  {
    id: 2,
    title: 'Le Dîner Solitaire',
    description: 'Manger seul dans un resto chic. Téléphone éteint. Être à l\'aise avec soi-même.',
    category: 'public_introspection',
    targetTraits: { emotionalStability: 0.8, extraversion: 0.3 },
    comfortLevel: 'high',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 90,
    fallbackQuestId: 9,
  },
  {
    id: 3,
    title: 'La Nuit Étoilée',
    description: 'Passer une nuit sous les étoiles, sans distraction, juste avec ses pensées.',
    category: 'sensory_deprivation',
    targetTraits: { openness: 0.6, conscientiousness: 0.5 },
    comfortLevel: 'high',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 600,
    fallbackQuestId: 9,
  },
  {
    id: 4,
    title: 'L\'Explorateur Local',
    description: 'Aller dans une ville minuscule et parler à au moins une personne locale.',
    category: 'exploratory_sociability',
    targetTraits: { extraversion: 0.7, agreeableness: 0.6, openness: 0.7 },
    comfortLevel: 'high',
    requiresOutdoor: true,
    requiresSocial: true,
    minimumDurationMinutes: 240,
    fallbackQuestId: 13,
  },
  {
    id: 5,
    title: 'Le Point Culminant',
    description: 'Monter au point le plus haut de la ville et réfléchir à sa direction de vie.',
    category: 'physical_existential',
    targetTraits: { openness: 0.6, conscientiousness: 0.5 },
    comfortLevel: 'moderate',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 120,
    fallbackQuestId: 9,
  },
  {
    id: 6,
    title: 'L\'Entraînement de l\'Aube',
    description: 'S\'entraîner seul un dimanche matin pendant que tout le monde dort.',
    category: 'async_discipline',
    targetTraits: { conscientiousness: 0.9 },
    comfortLevel: 'moderate',
    requiresOutdoor: true,
    requiresSocial: false,
    minimumDurationMinutes: 60,
    fallbackQuestId: 9,
  },
  {
    id: 7,
    title: 'La Détox Digitale',
    description: 'Passer 24h sans réseaux sociaux et observer les changements cognitifs.',
    category: 'dopamine_detox',
    targetTraits: { emotionalStability: 0.7, conscientiousness: 0.8 },
    comfortLevel: 'high',
    requiresOutdoor: false,
    requiresSocial: false,
    minimumDurationMinutes: 1440,
  },
  {
    id: 8,
    title: 'Le Pont Humain',
    description: 'Lancer une vraie conversation avec un inconnu. Écouter vraiment.',
    category: 'active_empathy',
    targetTraits: { extraversion: 0.8, agreeableness: 0.8 },
    comfortLevel: 'high',
    requiresOutdoor: true,
    requiresSocial: true,
    minimumDurationMinutes: 30,
    fallbackQuestId: 12,
  },
  {
    id: 9,
    title: 'La Lettre au Futur',
    description: 'Écrire une lettre à la personne que l\'on veut devenir dans 5 ans.',
    category: 'temporal_projection',
    targetTraits: { openness: 0.5, conscientiousness: 0.6 },
    comfortLevel: 'low',
    requiresOutdoor: false,
    requiresSocial: false,
    minimumDurationMinutes: 45,
  },
  {
    id: 10,
    title: 'L\'Immersion Totale',
    description: 'Aller à un événement où l\'on ne connaît personne et rester jusqu\'à être à l\'aise.',
    category: 'hostile_immersion',
    targetTraits: { extraversion: 0.9, emotionalStability: 0.8 },
    comfortLevel: 'extreme',
    requiresOutdoor: true,
    requiresSocial: true,
    minimumDurationMinutes: 180,
    fallbackQuestId: 8,
  },
  {
    id: 11,
    title: 'Le Rayon de Soleil',
    description: 'Complimenter sincèrement cinq inconnus dans la même journée.',
    category: 'spontaneous_altruism',
    targetTraits: { agreeableness: 0.7, extraversion: 0.6 },
    comfortLevel: 'moderate',
    requiresOutdoor: true,
    requiresSocial: true,
    minimumDurationMinutes: 60,
    fallbackQuestId: 13,
  },
  {
    id: 12,
    title: 'La Reconnexion',
    description: 'Appeler un ancien ami et rallumer un lien laissé éteint.',
    category: 'relational_vulnerability',
    targetTraits: { agreeableness: 0.7, emotionalStability: 0.6 },
    comfortLevel: 'high',
    requiresOutdoor: false,
    requiresSocial: true,
    minimumDurationMinutes: 30,
  },
  {
    id: 13,
    title: 'Le Festin Altruiste',
    description: 'Cuisiner un repas pour quelqu\'un sans rien attendre en retour.',
    category: 'unconditional_service',
    targetTraits: { agreeableness: 0.8, conscientiousness: 0.6 },
    comfortLevel: 'low',
    requiresOutdoor: false,
    requiresSocial: true,
    minimumDurationMinutes: 120,
  },
];

export const INDOOR_QUEST_IDS = QUEST_TAXONOMY
  .filter((q) => !q.requiresOutdoor)
  .map((q) => q.id);

export const FALLBACK_QUEST_ID = 9;

/** Famille de quête (moteur) — libellé court, distinct du titre généré par l’IA */
export const QUEST_CATEGORY_LABEL_FR: Record<PsychologicalCategory, string> = {
  spatial_adventure: 'Déplacement & exploration',
  public_introspection: 'Présence en public',
  sensory_deprivation: 'Immersion & calme',
  exploratory_sociability: 'Rencontre & lieu',
  physical_existential: 'Corps & perspective',
  async_discipline: 'Discipline & rythme',
  dopamine_detox: 'Rythme & écrans',
  active_empathy: 'Connexion & écoute',
  temporal_projection: 'Projection',
  hostile_immersion: 'Immersion sociale',
  spontaneous_altruism: 'Geste & chaleur',
  relational_vulnerability: 'Liens proches',
  unconditional_service: 'Don & partage',
};

export function questFamilyLabel(category: string | undefined | null): string | null {
  if (!category) return null;
  const k = category as PsychologicalCategory;
  return k in QUEST_CATEGORY_LABEL_FR ? QUEST_CATEGORY_LABEL_FR[k] : null;
}
